apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-batch-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-batch-task
  template:
    metadata:
      labels:
        app: spring-batch-task
    spec:
      containers:
        - name: spring-batch-task-container
          image: your-container-registry/spring-batch-task-image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-batch-task-service
spec:
  selector:
    app: spring-batch-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer